### ISSUE TITLE
Issue with database updating

### ISSUE THREAD

**Issue by NazarHomeniuk** [Nazar1488/hello-world#6]
When program restarting, new cars isn't updating. We must solve this issue. Could you have any suggestions?

**Comment by MaxKostiv** [comment]
yes

**Comment by NazarHomeniuk** [comment]
@MaxKostiv Describe me your idea, please

**Comment by MaxKostiv** [comment]
You are too dull to understand this

**Comment by NazarHomeniuk** [comment]
@MaxKostiv idiot.

**Comment by Nazar1488** [comment]
Resolved

**Comment by Nazar1488** [comment]
"Resolved #6"

**Comment by Nazar1488** [comment]
This close
